### PR TITLE
deduplicate functions

### PR DESCRIPTION
**Pull request by mulimoen**
This recombines inlined functions, as rust can inline across files.

I was not quite sure where to put the resulting functions, so I put them at the end of lib.rs. Please let me know if you would like me to move them somewhere more appropriate!

### CODE REVIEW

**Comment by crlf0710** [comment]
Need a rebase~

**Comment by crlf0710** [comment]
According the original c code. there can be a new module called `xetex_xetexd`, and `is_non_discardable_node`, `print_c_string`, `is_char_node` call live within that. The others comes from core_* files, so maybe just leave them at the toplevel of the crate.

**Comment by mulimoen** [comment]
rebased

**Comment by crlf0710** [comment]
Great, thanks.

**Pull request merged**
