### PR TITLE
fix typo in try_break

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
@Mrmaxmeier

**Comment by Mrmaxmeier** [comment]
https://tt.ente.ninja/#/compare/1be34e52348645ff1d22d7fc1a49db8b28d5afaf/a6f58e278ac0cec53e91a9a0d73bd3c3ab025d1f
The bot is running but didn't create a check run here for some reason. @burrbull Did you add the Github app to your fork/repo?

**Comment by burrbull** [comment]
изображение
Yes, I had done this several months ago.

**Comment by Mrmaxmeier** [comment]
Hmm, the other pull requests worked fine. It's probably racy and depends on which web-hook is delivered first.

**Comment by burrbull** [comment]
Merging this

**Pull request merged**
