### PR TITLE
fix osx build

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
```
Installing Homebrew Packages

6.56s$ rvm $brew_ruby do brew bundle --verbose --global

/usr/local/bin/brew tap homebrew/bundle

==> Tapping homebrew/bundle

Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...

remote: Enumerating objects: 96, done.

remote: Counting objects: 100% (96/96), done.

remote: Compressing objects: 100% (88/88), done.

remote: Total 96 (delta 5), reused 22 (delta 1), pack-reused 0

Receiving objects: 100% (96/96), 49.72 KiB | 2.76 MiB/s, done.

Resolving deltas: 100% (5/5), done.

Tapped (105 files, 262KB).

Error: Unknown command: bundle
```

**Comment by burrbull** [comment]
cc @crlf0710 
This workarounds mac build failure (looks like bug in travis).

But windows build also broken.

**Comment by crlf0710** [comment]
Seems good,  so specifying those libraries as dependencies is different from installing them using brew manually?

**Comment by crlf0710** [comment]
r=me when CI is green.

**Comment by burrbull** [comment]
CI is not green because `windows` build doesn't pass `latex_to_pdf` test for several days.

**Comment by burrbull** [comment]
I've also tried to use GHA instead of `travis` and got same problem on windows:
https://github.com/burrbull/tectonic/runs/750987648?check_suite_focus=true

**Comment by crlf0710** [comment]
Ok... So let's merge this then. I'll try to find some time to investigate on the windows build.

**Pull request merged**
