### PR TITLE
More refactoring fixes

### PR DESCRIPTION
**Pull request by Mrmaxmeier**
This fixes refactoring fallout introduced in #107 and #129

### CODE REVIEW

**Comment by crlf0710** [comment]
Thanks!

**Comment by crlf0710** [comment]
@Mrmaxmeier Could you help rerun the current `oxidize` branch with the arxiv dataset? If the current commit proves ok, i want to add a tag or something to mark it.

**Comment by mulimoen** [comment]
Please hold off on rerunning the tests until #132 is merged

**Comment by Mrmaxmeier** [comment]
#132 fixed some (13) of the remaining regressions. There's still about 50 left though.

Here's the current state (a8d94d2d):
https://tt.ente.ninja/#/compare/master-v0.1.11-420-ge0c3b418/oxidize-v0.1.11-717-ga8d94d2d

**Pull request merged**
