### PR TITLE
slices in cff pack, card8/16

### PR DESCRIPTION
**Pull request by burrbull**
I started from small changes. But... Domino effect.

### CODE REVIEW

**Comment by crlf0710** [comment]
Mmm, i feel a little controversial on the card8/card16 changes.  For the CFF font format, it has five data formats, called Card8, Card16, Offset, OffSize, and SID. See also the 5176.CFF.pdf .

I think the best way forward is to keep it and define:
struct Card8(u8);
struct Card16(u16);
etc

**Comment by burrbull** [comment]
`card8` and `card16` unlike `Offsize`, SID` don't carry any information aside from "1-byte unsigned number". I'm sure Adobe use them because awful C type system.

**Comment by crlf0710** [comment]
Fair point, let's replace them then. Need a rebase~

**Comment by burrbull** [comment]
Can you rerun travis?

**Comment by crlf0710** [comment]
Merging

**Pull request merged**
