### PR TITLE
Fixes for #144

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by cormacrelf** [comment]
#144

**Comment by crlf0710** [comment]
It's ... a little unfortunate of having to spread a lifetime parameter everywhere...

**Comment by cormacrelf** [comment]
Std File doesn’t require mut, and can be cloned with try_clone, because it simply wraps a raw file descriptor.

Are these handles similar? They just wrap a raw pointer, but does the main tectonic program require these pointers used over the bridge to be mut (in the sense of being unique pointers and accessed by one thread at a time) to work properly? I’m guessing yes, because of the indirection code. Does it also require mut over all the methods? Maybe some of them? This would be much simpler if the indirection code lived in the bridge and these things could be checked by the compiler. I have a hunch that changing up the way handles are used would mean more of them could be owned rather than borrowed. 

Lastly, do we even need wrapped input handles for fonts?

**Comment by burrbull** [comment]
I'm planning to move `ttstub_input_close` into wrapper's `drop` and delete all `clone`s.
But it's still one problem here. Some of owners of `handle`s (like `sfnt`) are allocating by C.
As soon as we solve this problem all remaining `clone`s will disappear.

**Pull request merged**
