### PR TITLE
Fix build warnings

### PR DESCRIPTION
**Pull request by xcaptain**
Removed some unused variables, imports to clean build warnings.

### CODE REVIEW

**Comment by mulimoen** [comment]
All functions starting with `hb_` are FFI functions from harfbuzz, and we can not change the function signatures

**Comment by mulimoen** [comment]
There is a harfbuzz-sys crate which you can import the functions/signatures from

**Comment by crlf0710** [comment]
To use the rust `harfbuzz-sys` crate (maintained by servo i believe), we'll need to enable `icu` and `graphite2` optional dependencies within the cmake/cpp code, so some changes (maybe as crate features) may need to be added. I believe @ratmice has done similar efforts before on both the `harfbuzz-sys` crate and `graphite2-sys` crate. Maybe we can ask him what the current status are.

**Comment by xcaptain** [comment]
So those `hb_` functions in `xetex_font_info.rs` are generated from harfbuzz using c2rust right? I think it's better to use `harfbuzz-sys`. I will close this pull request first and take a look at `harfbuzz-sys` later.

**Comment by ratmice** [comment]
@xcaptain sorry I didn't see this earlier,  I've currently got a bunch of rather ugly forks,
Which bubble up a bunch of flags to the tectonic build.rs via environment variables.

Current status is that it works on some platforms/CI services, like travis and my local machine,
But I had troubles getting it working on azure, and troubles figuring out exactly why -- then took a break from it, I didn't really want to try upstreaming anything yet since it'll all need a cleanup pass once it works everywhere.

Let me know if it helps for me to rebase or merge to more recent upstream for any of these!

https://github.com/ratmice/rust-harfbuzz
https://github.com/ratmice/graphite2-sys-rust
https://github.com/ratmice/rust-icu
https://github.com/ratmice/tectonic

**Pull request closed without merging**
