### PR TITLE
x{m,c}alloc_array

### PR DESCRIPTION
**Pull request by mulimoen**

### CODE REVIEW

**Comment by burrbull** [comment]
maybe `xmalloc_cstring` as it allocate additional byte for `\0` ?

**Comment by mulimoen** [comment]
the original `xmalloc_array` always allocates an extra element for all types, not just char or u8

**Comment by burrbull** [comment]
> the original `xmalloc_array` always allocates an extra element for all types, not just char or u8

Ok

**Comment by burrbull** [comment]
Conflict

**Comment by mulimoen** [comment]
rebased

**Pull request merged**
