### PR TITLE
Xetex consts, functions & Option for pointers

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
@Mrmaxmeier need to test this with arxiv

**Comment by Mrmaxmeier** [comment]
_closing and reopening to trigger the bot_

**Comment by crlf0710** [comment]
This is huge... by the way, what does the "[DNM]" in the title mean?

**Comment by burrbull** [comment]
yes, this is huge :)
dnm - do not merge
work still in progress

in this PR I've restored almost all constants in xetex0, math, etc.
Also I try to replace `i32` addresses in linked list with `usize` and `Option<usize>` for variables, that can have TEX_NULL value.

**Comment by burrbull** [comment]
What situation with windows build?

**Comment by crlf0710** [comment]
> What situation with windows build?

Created #264 . Not sure what is the cause yet...

**Comment by burrbull** [comment]
I think it's time to test, fix and merge this.
cc @Mrmaxmeier

**Comment by Mrmaxmeier** [comment]
> I think it's time to test, fix and merge this.
> cc @Mrmaxmeier

I've queued a bunch of jobs that should fix the bot. These runs might take a while to finish though. Let's see...

**Comment by burrbull** [comment]
Can we tune `bors-ng` to use `bors try` for triggering checks?

**Comment by burrbull** [comment]
Looks like endless cycle somewhere in 1702.00217 and 1702.07062

**Comment by Mrmaxmeier** [comment]
Huh, this test run seems stuck: https://tt.ente.ninja/#/compare/330096a263651777716ca012732b8a0638cdd069/99ce1504f13f03351fc690cee2c1445c871c299f
It looks like the CI box has been having DNS issues.

> Can we tune bors-ng to use bors try for triggering checks?

A comment-based system might be nice. Running CI on every push should generally work though.
I'll push an empty commit to your branch to check.. Feel free to force-push over it.


Edit: Something is broken with pushing results to GitHub. As a workaround, you can use direct links to the report via the full commit hash: https://tt.ente.ninja/#/compare/330096a263651777716ca012732b8a0638cdd069/88dd617fd2ef975e9221e034f0696ea32f0067aa

**Comment by burrbull** [comment]
I would like this system to have 2 more functions:
1 - stop option on website
2 - the ability to run it with `git bisect` on one of arxiv files

**Comment by burrbull** [comment]
All founded bugs are fixed!

**Comment by burrbull** [comment]
I merge this.

**Pull request merged**
