### PR TITLE
pdf_dict, array, stream has/get/get_mut 

### PR DESCRIPTION
**Pull request by burrbull**
split
`pdf_lookup_dict()` on `.as_dict().has()`, `.as_dict().get()` and `.as_dict().get_mut()`
`pdf_get_array` on `.as_array().get()` and `.as_array().get_mut()`
`stream_dict` on `.as_stream().get_dict()` and `.as_stream().get_dict_mut()`

use `output_xref: Vec<xref_entry>`

### CODE REVIEW

**Comment by crlf0710** [comment]
While this seems good, why don't you just change these into methods...

**Comment by cormacrelf** [comment]
@crlf0710 they are methods on pdf_obj in #176, but practically nowhere in the code is there a rust reference, only raw mut pointers, so they are difficult to call at the moment.

**Comment by burrbull** [comment]
Ok. I'll try.

**Comment by crlf0710** [comment]
Seems good, merging~

**Pull request merged**
