### PR TITLE
use slices in specials::spc_arg & more parse traits

### PR DESCRIPTION
**Pull request by burrbull**
Depends on #147

### CODE REVIEW

**Comment by burrbull** [comment]
Rebased. Last 2 commits moved into #163

**Comment by burrbull** [comment]
@Mrmaxmeier I need your tests and maybe help.

**Comment by Mrmaxmeier** [comment]
https://tt.ente.ninja/#/compare/oxidize-v0.1.11-767-g871978d5/new2-v0.1.11-773-g4f25140a

Most of the regressions are from font names being encoded as `Times#20New#20Roman` instead of `Times New Roman`.

**Comment by burrbull** [comment]
Looks like I use `CStr::from_bytes_with_nul` in wrong way.

**Comment by burrbull** [comment]
@Mrmaxmeier can you retest?

**Comment by Mrmaxmeier** [comment]
No regressions :+1: :shipit:

**Pull request merged**
