### PR TITLE
pdf_lookup_dict

### PR DESCRIPTION
**Pull request by burrbull**
`pdf_lookup_dict` now takes `&str` key and return `Option`
`pdf_name_value` return `&CStr`

### CODE REVIEW

**Comment by burrbull** [comment]
`pdf_add_dict` also takes `&str`

**Comment by crlf0710** [comment]
Need a rebase. I plan to merge this after the rebase, however please note that this API change is losing its generality. 

In PDF the dictionary key is a name object, which doesn't have to obey the rules of utf8 encoding, instead it has it own forbidden bytes (delimiter or white-space characters), so this API can't be the final form, i think.

**Comment by crlf0710** [comment]
See also:
https://docs.rs/lopdf/0.23.0/lopdf/struct.Dictionary.html#method.get

**Comment by burrbull** [comment]
You mean we should pass `&[u8]` and `b'string'` respectively?
I think it is not hard to do.

**Comment by crlf0710** [comment]
Yes, i think &[u8] is better than &str at this case. And maybe we want to "intern" them somehow. But let's leave that to the future. I'll merge this first.

**Pull request merged**
