### PR TITLE
Fix part of #195.

### PR DESCRIPTION
**Pull request by crlf0710**
It turns out that a logical not is missing in current code.

### CODE REVIEW

**Comment by crlf0710** [comment]
For the first file in #195, it turns out our coordinate transformation is incorrect. Maybe we should have just used something like `euclid`.

**Comment by crlf0710** [comment]
Mmmm, while i'm quite confident about the fix itself... Is there any way to quickly find out whether all the result differences are actually an improvment?

**Comment by Mrmaxmeier** [comment]
Nice find! :tada: 

> Mmmm, while i'm quite confident about the fix itself... Is there any way to quickly find out whether all the result differences are actually an improvment?

I'm currently running a test run comparing `tectonic-typesetting#master` vs the `oxidize` branch.

master vs 55fa14c:
https://tt.ente.ninja/#/compare/master-a9958b322b9f46bcbd7e064b156362fe989fd8d1/55fa14c07b4ca4ba4144bc1c40b77312bc57be3c

master vs 0ba4b44:
https://tt.ente.ninja/#/compare/master-a9958b322b9f46bcbd7e064b156362fe989fd8d1/0ba4b44ac313f8636f4927bd658e07ac3527481d

It seems very promising so far. ~I'll update once the run has finished.~ The changes seem 100% fine.

```console
$ python3 ../base-reg-fix.py master-a9958b322b9f46bcbd7e064b156362fe989fd8d1.jsonl 55fa14c07b4ca4ba4144bc1c40b77312bc57be3c.jsonl 0ba4b44ac313f8636f4927bd658e07ac3527481d.jsonl
total regressed (reg): 427
total regressed (fix): 270
    fixed regressions: 157
      new regressions: 0
changed but not fixed: 9
```

**Comment by burrbull** [comment]
https://github.com/crlf0710/tectonic/blob/f55d0f6d0716f8e913e59f7bb802a6c09cba4880/engine/src/bibtex.rs#L795
missing space after "file"

**Comment by Mrmaxmeier** [comment]
> https://github.com/crlf0710/tectonic/blob/f55d0f6d0716f8e913e59f7bb802a6c09cba4880/engine/src/bibtex.rs#L795
> 
> missing space after "file"

This change was introduced here: https://github.com/tectonic-typesetting/tectonic/pull/485
Do we have some kind of strategy of merging back into tectonic-typestting/tectonic or picking up the changes for this fork?

**Comment by cormacrelf** [comment]
1. I like Euclid. Maybe sketch out a plan for which types get mapped to which Euclid types. I’m not sure how well that interacts with the fixed point arithmetic though — none of that is really typechecked at the moment, it’s a tripping hazard for refactoring, and I am unsure how much discipline has gone into tracking the scaling factors which are multiplied when you multiply. I’d be happier with the `fixed` crate replacing the Fixed type and providing the scalar for some `euclid` type aliases. I’d be interested to see how a short PR with `type Fixed = fixed::types::I16F16` and D2Fix/Fix2D rewritten goes. I will merge my fonts thing first as it centralises this a bit.
2. We don’t have a strategy except “merge this at some point”. It would help for someone to watch the main repo. Could also make a GHA cron job to make a rollup PR, may be overkill.

**Comment by burrbull** [comment]
With euclid I see one problem. It represents rectangle as Rect(start Point, Size), where Bbox in TeX is Rect(start Point, end Point).
We can add many new bugs while porting.

**Comment by crlf0710** [comment]
So, i'll just merge this. I'll open new issues for the bibtex space change and the possibility of using an existing crate to provide coordinate types.

**Pull request merged**
