### PR TITLE
Change time

### PR DESCRIPTION
**Pull request by mulimoen**
Gets rid of gmtime/gmtime_r and other functions.

Output format is not stricly compliant with the original, but not sure whether this matters much,
"D:201909201805+01'00'" vs "D:201909201805+0100"

### CODE REVIEW

**Comment by mulimoen** [comment]
Now formatting exactly as before the change

**Comment by cormacrelf** [comment]
Would be good to know if that time format string is defined in a pdf spec somewhere

But looks like you’ve done well

**Comment by crlf0710** [comment]
@cormacrelf It's in section 3.8.3 Dates within PDF reference 1.7, if that's useful to you.
there's an example in the book: D:199812231952-08'00'

**Comment by crlf0710** [comment]
Let's merge this.

**Pull request merged**
