### PR TITLE
XeTeX Nodes

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
cc @Mrmaxmeier 
Run test, please.

**Comment by burrbull** [comment]
cc @Mrmaxmeier

**Comment by Mrmaxmeier** [comment]
Needs a rebase on 37979cb when merged. The CI build was failing (#269) and something broke again.

**Comment by burrbull** [comment]
@Mrmaxmeier it doesn't work again

**Comment by burrbull** [comment]
@Mrmaxmeier rerun tests on this branch, please.

**Comment by Mrmaxmeier** [comment]
> @Mrmaxmeier rerun tests on this branch, please.

Note: Statuscode `-99999` for https://arxiv.org/e-print/1702.00217 is a timeout. I should probably change it to something more descriptive :slightly_smiling_face: 

This particular test-case seems to take 440 seconds normally but timed out at 600 seconds due to two concurrent CI runs.

**Comment by burrbull** [comment]
I remember 00217. It is compiling ve-e-e-ery slow.
I would disable it.

**Pull request merged**
