### PR TITLE
rewrite some gotos

### PR DESCRIPTION
**Pull request by mulimoen**
See also #38

### CODE REVIEW

**Comment by mulimoen** [comment]
@burrbull

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
This is big change. Can someone else review?

**Comment by mulimoen** [comment]
Seems a lot bigger than it is. Try comparing directly to the C source

**Comment by burrbull** [comment]
LGTM. If no one is against, I will merge this.

**Review by cormacrelf — APPROVED** [review]
LGTM as well

**Pull request merged**
