### PR TITLE
use `OutputHandleWrapper` and `io::Write` instead of `rust_output_handle_t`

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by ThomasdenH** [comment]
If the raw handle is never used directly, it can even be closed when the wrapper drops.

**Comment by burrbull** [comment]
> If the raw handle is never used directly, it can even be closed when the wrapper drops.

Not sure I understood what you mean.

**Comment by ThomasdenH** [comment]
If you `impl Drop` on the wrapper and close the bridge, that will automatically happen when the wrapper goes out of scope.

**Comment by burrbull** [comment]
> If you `impl Drop` on the wrapper and close the bridge, that will automatically happen when the wrapper goes out of scope.

Don't know what to do with:
https://github.com/crlf0710/tectonic/blob/62cf423597fafff6f487b26abc53c7a3a4dfd322/engine/src/xetex_shipout.rs#L3573

And I afraid we need to rewrite some logic to close bridges automatically.

**Comment by crlf0710** [comment]
Generally seems good, but i see there's some Option<OutputHandleWrapper> used. Is it the intention that OutputHandleWrapper will never be null inside? If so, it would be great if we can change the rust_output_handle_t's definition to NonNull.

**Comment by burrbull** [comment]
> Generally seems good, but i see there's some Option used. Is it the intention that OutputHandleWrapper will never be null inside? If so, it would be great if we can change the rust_output_handle_t's definition to NonNull.

Now we use `OutputHandleWrapper(NonNull<libc::c_void>)`.

**Comment by crlf0710** [comment]
Seems good~

**Comment by burrbull** [comment]
Last commit should fix #82.

cc @mulimoen
can you test?

**Comment by cormacrelf** [comment]
Wasn't the only reason to use `NonNull` so that `Option` could do its null pointer optimisation and be one word in memory instead of two? Without the `Option` wrapper, there isn't much point using it.

**Comment by mulimoen** [comment]
I am getting a panic with the master branch atm, so will try when #109 is fixed

**Comment by mulimoen** [comment]
This PR fixes #82

**Comment by burrbull** [comment]
Rebased.

**Comment by crlf0710** [comment]
Merging~ Thanks

**Pull request merged**
