### PR TITLE
avoid external linkage

### LINKED ISSUE #53: Fail on building in release mode
```
error: internal compiler error: src/librustc_codegen_llvm/consts.rs:218: Conflicting symbol names for static?
   --> engine/src/xetex_ini.rs:758:1
    |
758 | pub static mut mem: *mut memory_word = 0 as *const memory_word as *mut memory_word;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:578:9
```

### PR DESCRIPTION
**Pull request by mulimoen**
accesses parameters and functions through the module system, instead of through external linkage.

Fixes #53 somehow??

### CODE REVIEW

**Review by cormacrelf — APPROVED** [review]
LGTM. Nice line stats.

**Comment by mulimoen** [comment]
Think I broke the mac compilation, but the errors should be very straight forwards to fix.

**Comment by cormacrelf** [comment]
xetex_aatfont was using xmalloc(usize) etc, where everything else has xmalloc(u64). Better to be usize, but not sure if worth the bother for the rest of the codebase if we're actually trying to eventually use Box and Vec to do allocation. So probably just `as u64` in there.

Otherwise, `git apply` this

```diff
diff --git a/engine/src/xetex_aatfont.rs b/engine/src/xetex_aatfont.rs
index 5f0e73e2..0fe1da74 100644
--- a/engine/src/xetex_aatfont.rs
+++ b/engine/src/xetex_aatfont.rs
@@ -357,8 +357,9 @@ pub mod cf_prelude {
 
 use crate::core_memory::{xcalloc, xmalloc};
 use crate::xetex_ext::{
-    font_feature_warning, print_chars, readCommonFeatures, read_double, D2Fix, Fix2D,
+    print_chars, readCommonFeatures, read_double, D2Fix, Fix2D,
 };
+use crate::xetex_xetex0::font_feature_warning;
 use crate::xetex_ini::memory_word;
 use crate::xetex_ini::{
     font_area, font_layout_engine, font_letter_space, loaded_font_flags, loaded_font_letter_space,
diff --git a/engine/src/xetex_layout_engine.rs b/engine/src/xetex_layout_engine.rs
index f891e14a..efa0307d 100644
--- a/engine/src/xetex_layout_engine.rs
+++ b/engine/src/xetex_layout_engine.rs
@@ -3,7 +3,7 @@ pub type XeTeXLayoutEngine = *mut XeTeXLayoutEngine_rec;
 #[cfg(not(target_os = "macos"))]
 pub type PlatformFontRef = *mut FcPattern;
 #[cfg(target_os = "macos")]
-pub type PlatformFontRef = CTFontDescriptorRef;
+pub type PlatformFontRef = crate::xetex_aatfont::cf_prelude::CTFontDescriptorRef;
 #[derive(Copy, Clone)]
 #[repr(C)]
 pub struct GlyphAssembly {
```

**Comment by mulimoen** [comment]
Thanks!

**Review by cormacrelf — APPROVED** [review]

**Comment by crlf0710** [comment]
Thanks~

**Pull request merged**
