### PR TITLE
Run rustfmt on all builds.

### LINKED ISSUE #207: Add a `rustfmt --check` to CI.
This will ensure further PRs have got the formatting correct before they lands.

### PR DESCRIPTION
**Pull request by crlf0710**
Closes #207

### CODE REVIEW

**Comment by burrbull** [comment]
Maybe it's better to make another travis task for `rustfmt`?

**Comment by crlf0710** [comment]
I think it's fast enough... I'll merge it first and move it to a separate task next time.

**Comment by burrbull** [comment]
When task fails, it's easier to detect cause when `rustfmt` does not affect on `test` task.

**Comment by crlf0710** [comment]
Opened #226

**Pull request merged**
