### PR TITLE
Remove extra match

### PR DESCRIPTION
**Pull request by chirsz-ever**
I replaced all code with pattern like that:
```rust
current_block = 1234;
match current_block {
    // ...
}
```
with the simplified version. They are all in `engine` folder.
Passed all tests.

### CODE REVIEW

**Comment by cormacrelf** [comment]
Another good improvement would be to change each c2rust state machine like these to enums, and give random names like WaxMagesty or SatedVernacular to all the states. Once you’re there you can start adding data to the enum variants and naming the states incrementally as you figure out what they mean.

**Comment by cormacrelf** [comment]
(Can we get a few pairs of eyes on this before merge? Maybe useful to compare to the reference sources.)

**Comment by crlf0710** [comment]
Thanks for the PR! However we're yet to come up with a way to "symbolize" these numbers. After the numbers get symbolized,  it'll be much easier to review this change :)

**Comment by chirsz-ever** [comment]
While I think It will be more easy to symbolize these numbers after these simplification. 
The review won't be a epic work, because totally the "extra match pattern" occur 56 times, and 37 of them are in bibtex::excute_fn which just Interprete "opcode" then excute corresponding function or a piece of code.

**Comment by crlf0710** [comment]
Could we split this PR into a series of smaller PRs? That'll make them easier to land.

**Comment by chirsz-ever** [comment]
Ok, I will split them by files.

**Pull request closed without merging**
