### PR TITLE
mpost STACK & token

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by cormacrelf** [comment]
Code looks good, but did you get a sense of how the stack works that you could share? Clearly all kinds of pdf objects are put on it, but why is it a stack, what is its purpose?

**Comment by burrbull** [comment]
> Code looks good, but did you get a sense of how the stack works that you could share? Clearly all kinds of pdf objects are put on it, but why is it a stack, what is its purpose?

I did not think about such a global issue.

**Comment by burrbull** [comment]
I don't know is 1024 size limit is principal or not.
Therefore, I did not delete this check.

**Comment by cormacrelf** [comment]
Alright. I suspect it has something to do with DVI being a stack-based programming language (not sure it is, but that would make sense).

**Pull request merged**
