### PR TITLE
spc_warn!

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by Mrmaxmeier** [comment]
It looks like this fixes most of the issues from the first run :+1:

https://tt.ente.ninja/#/compare/cli-only-cached-v0.1.11-419-gdb4e65b1/fixed-v0.1.11-682-g172fe472-dirty

**Comment by crlf0710** [comment]
Need a rebase~

**Comment by burrbull** [comment]
Done.

**Comment by crlf0710** [comment]
Merging~

**Pull request merged**
