### PR TITLE
Update project structure.

### PR DESCRIPTION
**Pull request by crlf0710**
Decouple the engine crate into three crates[bridge, dpx and engine].

### CODE REVIEW

**Comment by cormacrelf** [comment]
Is the idea that the bridge is eventually deleted? / tt_bridge_api_t becomes a trait with an impl in tectonic?

**Comment by crlf0710** [comment]
@cormacrelf I've not yet thought it entirely through, frankly i'm neithor very familiar yet with the details of dvipdfmx nor with xetex itself.

From my current understanding, the bridge serves three purposes (correct me if i'm wrong):
1. An interface between C and Rust (this usage is now obsolete)
2. Act as an interface of the program to user, supporting warnings and errors.
3. Act as an interface of the program to the file resource manager. The resources are buffered-on-disk or download-on-demand.

So i think i want to split 2 and 3, and for 2, i think a log-style system will be enough. for 3, yes, maybe some IO traits are good enough as an interface.

**Comment by cormacrelf** [comment]
It appears to be the bottleneck (not performance-limiting, but structural) of all of xetex's IO, except for system font loading, such that tectonic can redirect it with `OutputHandle` etc, and record it with an `IoEventBackend`, so it knows when to rerun the engine. I sense that a long way down the road, that need not be quite so transparent and filename-based. (Maybe it doesn't need to be IO at all.)

That's all mostly irrelevant, but since `bridge` is pretty small so not a big compile time-saver being in its own crate, and changing it will always require changing `engine` and `tectonic`, it's probably best to keep the code in `engine`.

**Comment by crlf0710** [comment]
the motivation of having a separate `bridge` crate is that the `dpx` crate have something as its dependencies. or else there will be circular dependencies with the two crates.

**Pull request merged**
